 package com.barry.common.core.enums;

/**
 * CountryCurrencyEnum
 *
 */
public enum CountryCurrencyEnum {
    /**
     * country, iso2, iso3
     */
    ANDORRA("AD", "AND", "EUR"),
    UNITED_ARAB_EMIRATES("AE", "ARE", "AED"),
    AFGHANISTAN("AF", "AFG", "AFN"),
    ANTIGUA_AND_BARBUDA("AG", "ATG", "XCD"),
    ANGUILLA("AI", "AIA", "XCD"),
    ALBANIA("AL", "ALB", "ALL"),
    ARMENIA("AM", "ARM", "AMD"),
    NETHERLANDS_ANTILLES("AN", "ANT", "ANG"),
    ANGOLA("AO", "AGO", "AOA"),
    ANTARCTICA("AQ", "ATA", ""),
    ARGENTINA("AR", "ARG", "ARS"),
    AMERICAN_SAMOA("AS", "ASM", "USD"),
    AUSTRIA("AT", "AUT", "EUR"),
    AUSTRALIA("AU", "AUS", "AUD"),
    ARUBA("AW", "ABW", "AWG"),
    ALAND_ISLAND("AX", "ALA", "EUR"),
    AZERBAIJAN("AZ", "AZE", "AZN"),
    BOSNIA_AND_HERZEGOVINA("BA", "BIH", "BAM"),
    BARBADOS("BB", "BRB", "BBD"),
    BANGLADESH("BD", "BGD", "BDT"),
    BELGIUM("BE", "BEL", "EUR"),
    BURKINA_FASO("BF", "BFA", "XOF"),
    BULGARIA("BG", "BGR", "BGN"),
    BAHRAIN("BH", "BHR", "BHD"),
    BURUNDI("BI", "BDI", "BIF"),
    BENIN("BJ", "BEN", "XOF"),
    SAINT_BARTHELEMY("BL", "BLM", "EUR"),
    BERMUDA("BM", "BMU", "BMD"),
    BRUNEI("BN", "BRN", "BND"),
    BOLIVIA("BO", "BOL", "BOB"),
    CARIBBEAN_NETHERLANDS("BQ", "BES", "USD"),
    BRAZIL("BR", "BRA", "BRL"),
    BAHAMAS("BS", "BHS", "BSD"),
    BHUTAN("BT", "BTN", "INR"),
    BOUVET_ISLAND("BV", "BVT", "EUR"),
    BOTSWANA("BW", "BWA", "BWP"),
    BELARUS("BY", "BLR", "BYN"),
    BELIZE("BZ", "BLZ", "BZD"),
    CANADA("CA", "CAN", "CAD"),
    COCOS_KEELING_ISLANDS("CC", "CCK", "AUD"),
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO("CD", "COD", "CDF"),
    CHANNEL_ISLANDS("CE", "CEX", "GBP"),
    CENTRAL_AFRICAN_REPUBLIC("CF", "CAF", "XAF"),
    REPUBLIC_OF_THE_CONGO("CG", "COG", "XAF"),
    SWITZERLAND("CH", "CHE", "CHF"),
    IVORY_COAST("CI", "CIV", "XOF"),
    COOK_ISLANDS("CK", "COK", "NZD"),
    CHILE("CL", "CHL", "CLP"),
    CAMEROON("CM", "CMR", "XAF"),
    CHINA("CN", "CHN", "CNY"),
    COLOMBIA("CO", "COL", "COP"),
    COSTA_RICA("CR", "CRC", "CRC"),
    CUBA("CU", "CUB", "CUP"),
    CAPE_VERDE("CV", "CPV", "CVE"),
    CURACAO("CW", "CUW", "ANG"),
    CHRISTMAS_ISLAND("CX", "CXR", "AUD"),
    CYPRUS("CY", "CYP", "EUR"),
    CZECH_REPUBLIC("CZ", "CZE", "CZK"),
    GERMANY("DE", "DEU", "EUR"),
    DJIBOUTI("DJ", "DJI", "DJF"),
    DENMARK("DK", "DNK", "DKK"),
    DOMINICA("DM", "DMA", "XCD"),
    DOMINICAN_REPUBLIC("DO", "DOM", "DOP"),
    ALGERIA("DZ", "DZA", "DZD"),
    ECUADOR("EC", "ECU", "USD"),
    ESTONIA("EE", "EST", "EUR"),
    EGYPT("EG", "EGY", "EGP"),
    WESTERN_SAHARA("EH", "ESH", "MAD"),
    ERITREA("ER", "ERI", "ERN"),
    SPAIN("ES", "ESP", "EUR"),
    ETHIOPIA("ET", "ETH", "ETB"),
    FINLAND("FI", "FIN", "EUR"),
    FIJI("FJ", "FJI", "FJD"),
    FALKLAND_ISLANDS("FK", "FLK", "FKP"),
    MICRONESIA_FEDERATED_STATES_OF("FM", "FSM", "USD"),
    FAROE_ISLANDS("FO", "FRO", "DKK"),
    FRANCE("FR", "FRA", "EUR"),
    GABON("GA", "GAB", "XAF"),
    UNITED_KINGDOM("GB", "GBR", "GBP"),
    GRENADA("GD", "GRD", "XCD"),
    GEORGIA("GE", "GEO", "GEL"),
    FRENCH_GUIANA("GF", "GUF", "EUR"),
    GUERNSEY("GG", "GGY", "GBP"),
    GHANA("GH", "GHA", "GHS"),
    GIBRALTAR("GI", "GIB", "GIP"),
    GREENLAND("GL", "GRL", "DKK"),
    GAMBIA("GM", "GMB", "GMD"),
    GUINEA("GN", "GIN", "GNF"),
    GUADELOUPE("GP", "GLP", "EUR"),
    EQUATORIAL_GUINEA("GQ", "GNQ", "XAF"),
    GREECE("GR", "GRC", "EUR"),
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS("GS", "SGS", "FKP"),
    GUATEMALA("GT", "GTM", "GTQ"),
    GUAM("GU", "GUM", "USD"),
    GUINEA_BISSAU("GW", "GNB", "XOF"),
    GUYANA("GY", "GUY", "GYD"),
    HONG_KONG("HK", "HKG", "HKD"),
    HEARD_ISLAND_AND_MCDONALD_ISLANDS("HM", "HMD", "AUD"),
    HONDURAS("HN", "HND", "HNL"),
    CROATIA("HR", "HRV", "HRK"),
    HAITI("HT", "HTI", "HTG"),
    HUNGARY("HU", "HUN", "HUF"),
    INDONESIA("ID", "IDN", "IDR"),
    IRELAND("IE", "IRL", "EUR"),
    ISRAEL("IL", "ISR", "ILS"),
    ISLE_OF_MAN("IM", "IMN", "GBP"),
    INDIA("IN", "IND", "INR"),
    DIEGO_GARCIA("IO", "IOT", "GBP"),
    IRAQ("IQ", "IRQ", "IQD"),
    IRANISLAMIC_REPUBLIC_OF("IR", "IRN", "IRR"),
    ICELAND("IS", "ISL", "ISK"),
    ITALY("IT", "ITA", "EUR"),
    JERSEY("JE", "JEY", "GBP"),
    JAMAICA("JM", "JAM", "JMD"),
    JORDAN("JO", "JOR", "JOD"),
    JAPAN("JP", "JPN", "JPY"),
    KENYA("KE", "KEN", "KES"),
    KYRGYZSTAN("KG", "KGZ", "KGS"),
    CAMBODIA("KH", "KHM", "KHR"),
    KIRIBATI("KI", "KIR", "AUD"),
    COMOROS("KM", "COM", "KMF"),
    ST__KITTS_AND_NEVIS("KN", "KNA", "XCD"),
    NORTH_KOREA("KP", "PRK", "KPW"),
    SOUTH_KOREA("KR", "KOR", "KRW"),
    KUWAIT("KW", "KWT", "KWD"),
    CAYMAN_ISLANDS("KY", "CYM", "KYD"),
    KAZAKHSTAN("KZ", "KAZ", "KZT"),
    LAOS("LA", "LAO", "LAK"),
    LEBANON("LB", "LBN", "LBP"),
    ST__LUCIA("LC", "LCA", "XCD"),
    LIECHTENSTEIN("LI", "LIE", "CHF"),
    SRI_LANKA("LK", "LKA", "LKR"),
    LIBERIA("LR", "LBR", "LRD"),
    LESOTHO("LS", "LSO", "LSL"),
    LITHUANIA("LT", "LTU", "EUR"),
    LUXEMBOURG("LU", "LUX", "EUR"),
    LATVIA("LV", "LVA", "EUR"),
    LIBYA("LY", "LBY", "LYD"),
    MOROCCO("MA", "MAR", "MAD"),
    MONACO("MC", "MCO", "EUR"),
    MOLDOVA_THE_REPUBLIC_OF("MD", "MDA", "MDL"),
    MONTENEGRO("ME", "MNE", "EUR"),
    SAINT_MARTIN_FRANCE("MF", "MAF", "EUR"),
    MADAGASCAR("MG", "MDG", "MGA"),
    MARSHALL_ISLANDS("MH", "MHL", "USD"),
    MACEDONIA("MK", "MKD", "MKD"),
    MALI("ML", "MLI", "XOF"),
    BURMA("MM", "MMR", "MMK"),
    MONGOLIA("MN", "MNG", "MNT"),
    MACAU("MO", "MAC", "MOP"),
    MARIANA_ISLAND("MP", "MNP", "USD"),
    MARTINIQUE("MQ", "MTQ", "EUR"),
    MAURITANIA("MR", "MRT", "MRU"),
    MONTSERRAT("MS", "MSR", "XCD"),
    MALTA("MT", "MLT", "EUR"),
    MAURITIUS("MU", "MUS", "MUR"),
    MALDIVES("MV", "MDV", "MVR"),
    MALAWI("MW", "MWI", "MWK"),
    MEXICO("MX", "MEX", "MXN"),
    MALAYSIA("MY", "MYS", "MYR"),
    MOZAMBIQUE("MZ", "MOZ", "MZN"),
    NAMIBIA("NA", "NAM", "NAD"),
    NEW_CALEDONIA("NC", "NCL", "XPF"),
    NIGER_THE("NE", "NER", "XOF"),
    NORFOLK_ISLAND("NF", "NFK", "AUD"),
    NIGERIA("NG", "NGA", "NGN"),
    NICARAGUA("NI", "NIC", "NIO"),
    NETHERLANDS("NL", "NLD", "EUR"),
    NORWAY("NO", "NOR", "NOK"),
    NEPAL("NP", "NPL", "NPR"),
    NAURU("NR", "NRU", "AUD"),
    NIUE("NU", "NUI", "NZD"),
    NEW_ZEALAND("NZ", "NZL", "NZD"),
    OMAN("OM", "OMN", "OMR"),
    PANAMA("PA", "PAN", "PAB"),
    PERU("PE", "PER", "PEN"),
    FRENCH_POLYNESIA("PF", "PYF", "XPF"),
    PAPUA_NEW_GUINEA("PG", "PNG", "PGK"),
    PHILIPPINES("PH", "PHL", "PHP"),
    PAKISTAN("PK", "PAK", "PKR"),
    POLAND("PL", "POL", "PLN"),
    SAINT_PIERRE_AND_MIQUELON("PM", "SPM", "EUR"),
    PITCAIRN_ISLANDS("PN", "PCN", "NZD"),
    PUERTO_RICO("PR", "PRI", "USD"),
    PALESTINE("PS", "PSE", ""),
    PORTUGAL("PT", "PRT", "EUR"),
    PALAU("PW", "PLW", "USD"),
    PARAGUAY("PY", "PRY", "PYG"),
    QATAR("QA", "QAT", "QAR"),
    REUNION("RE", "REU", "EUR"),
    ROMANIA("RO", "ROU", "RON"),
    SERBIA("RS", "SRB", "RSD"),
    RUSSIA("RU", "RUS", "RUB"),
    RWANDA("RW", "RWA", "RWF"),
    SAUDI_ARABIA("SA", "SAU", "SAR"),
    SOLOMON_ISLANDS("SB", "SLB", "SBD"),
    SEYCHELLES("SC", "SYC", "SCR"),
    SUDAN("SD", "SDN", "SSP"),
    SWEDEN("SE", "SWE", "SEK"),
    SINGAPORE("SG", "SGP", "SGD"),
    ST__HELENA("SH", "SHN", "SHP"),
    SLOVENIA("SI", "SVN", "EUR"),
    SVALBARD_OG_JAN_MAYEN("SJ", "SJM", "NOK"),
    SLOVAKIA("SK", "SVK", "EUR"),
    SIERRA_LEONE("SL", "SLE", "SLL"),
    SAN_MARINO("SM", "SMR", "EUR"),
    SENEGAL("SN", "SEN", "XOF"),
    SOMALIA("SO", "SOM", "SOS"),
    SURINAM("SR", "SUR", "SRD"),
    SOUTH_SUDAN("SS", "SSD", "SSP"),
    SAO_TOME_AND_PRINCIPE("ST", "STP", "STN"),
    EL_SALVADOR("SV", "SLV", "SVC"),
    SINT_MAARTEN("SX", "SXM", "ANG"),
    SYRIA("SY", "SYR", "SYP"),
    SWAZILAND("SZ", "SWZ", "SZL"),
    TURKS_AND_CAICOS_ISLANDS("TC", "TCA", "USD"),
    CHAD("TD", "TCD", "XAF"),
    FRENCH_SOUTHERN_TERRITORIES("TF", "ATF", "EUR"),
    TOGO("TG", "TGO", "XOF"),
    THAILAND("TH", "THA", "THB"),
    TAJIKISTAN("TJ", "TJK", "TJS"),
    TOKELAU("TK", "TKL", "NZD"),
    EAST_TIMOR("TL", "TLS", "USD"),
    TURKMENISTAN("TM", "TKM", "TMT"),
    TUNISIA("TN", "TUN", "TND"),
    TONGA("TO", "TON", "TOP"),
    TURKEY("TR", "TUR", "TRY"),
    TRINIDAD_AND_TOBAGO("TT", "TTO", "TTD"),
    TUVALU("TV", "TUV", "AUD"),
    TAIWAN("TW", "TWN", "TWD"),
    TANZANIA("TZ", "TZA", "TZS"),
    UKRAINE("UA", "UKR", "UAH"),
    UGANDA("UG", "UGA", "UGX"),
    UNITED_STATES_MINOR_OUTLYING_ISLANDS("UM", "UMI", "USD"),
    UNITED_STATES("US", "USA", "USD"),
    URUGUAY("UY", "URY", "UYU"),
    UZBEKISTAN("UZ", "UZB", "UZS"),
    VATICAN_CITY("VA", "VAT", "EUR"),
    ST__VINCENT_AND_THE_GRENADINES("VC", "VCT", "XCD"),
    VENEZUELA("VE", "VEN", "VEF"),
    BRITISH_VIRGIN_ISLANDS("VG", "VGB", "USD"),
    VIRGIN_ISLANDS("VI", "VIR", "USD"),
    VIETNAM("VN", "VNM", "VND"),
    VANUATU("VU", "VUT", "VUV"),
    WALLIS_AND_FUTUNA("WF", "WLF", "XPF"),
    SAMOA("WS", "WSM", "WST"),
    KOSOVO("XK", "XKX", "EUR"),
    YEMEN("YE", "YEM", "YER"),
    MAYOTTE("YT", "MYT", "EUR"),
    YUGOSLAVIA("YU", "YUG", "YUN"),
    SOUTH_AFRICA("ZA", "ZAF", "ZAR"),
    ZAMBIA("ZM", "ZMB", "ZMW"),
    ZAIRE("ZR", "ZAR", "ZRN"),
    ZIMBABWE("ZW", "ZWE", "ZWL"),
    ;
    private final String iso2;
    private final String iso3;
    private final String currency;

    CountryCurrencyEnum(String iso2, String iso3, String currency) {
        this.iso2 = iso2;
        this.iso3 = iso3;
        this.currency = currency;
    }

    public String getIso2() {
        return iso2;
    }

    public String getIso3() {
        return iso3;
    }

    public String getCurrency() {
        return currency;
    }

    public static CountryCurrencyEnum currencyOf(String currency) {
        for (CountryCurrencyEnum value : CountryCurrencyEnum.values()) {
            if (value.getCurrency().equalsIgnoreCase(currency)) {
                return value;
            }
        }
        return null;
    }

    public static CountryCurrencyEnum isoOf(String iso) {
        for (CountryCurrencyEnum value : CountryCurrencyEnum.values()) {
            if (value.getIso2().equalsIgnoreCase(iso) || value.getIso3().equalsIgnoreCase(iso)) {
                return value;
            }
        }
        return null;
    }
}
